const ROLE_HIERARCHY = {
  PRESIDENT: 9,
  MINISTRE: 8,
  MINISTRE_DELEGUE: 8,
  MINISTRE_DETAT: 8,
  SECRETAIRE_GENERAL: 7,
  DIRECTEUR_GENERAL: 6,
  DIRECTEUR: 5,
  SOUS_DIRECTEUR: 4,
  CHEF_DE_DIVISION: 4,
  CHEF_DE_SERVICE: 3,
  CHEF_DE_BUREAU: 2,
  CADRE: 1
};

const ROLE_EQUIVALENCIES = {
  SOUS_DIRECTEUR: ['CHEF_DE_DIVISION'],
  MINISTRE: ['MINISTRE_DELEGUE', 'MINISTRE_DETAT']
};

module.exports = { ROLE_HIERARCHY, ROLE_EQUIVALENCIES };